language:
  - cpp
  - c
compiler:
  - gcc
install:
  - sudo apt-get install libqt4-dev qt4-qmake autoconf automake libtool autopoint
before_script:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test 
  - sudo apt-get update
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.6 60 --slave /usr/bin/g++ g++ /usr/bin/g++-4.6 
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.7 40 --slave /usr/bin/g++ g++ /usr/bin/g++-4.7 
  - sudo update-alternatives --config gcc
  - gcc --version
  - cd commander 
  - autoreconf -if
  - ./configure
script: make && make check