language: cpp
compiler:
  - gcc
install:
  - sudo apt-get install libqt4-dev qt4-qmake libtool
before_script:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test # GCC 4.7
  - sudo apt-get -qq update
  - '[[ $CC == "clang" ]] && exit 1 || [[ $CC == "gcc" ]]
      && sudo apt-get -qq install gcc-4.7
      && export CXX=g++-4.7
      && export CC=gcc-4.7'
  - gcc --version
script: # no script yet