language:
  - cpp
  - c
compiler:
  - gcc
install:
  - sudo apt-get update
  - sudo apt-get install gcc-4.7 libqt4-dev qt4-qmake autoconf automake libtool autopoint
before_script:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test # GCC 4.7
script: cd commander && autoreconf -if && ./configure && make && make check