language:
  - cpp
  - c
compiler:
  - gcc
install:
  - sudo apt-get install gcc-4.7 libqt4-dev qt4-qmake autoconf automake libtool autopoint
before_script:
  - gcc-4.7.0 --verision
  - gcc-4.7 --verision
  - export CC=gcc-4.7
  - gcc --version
  - cd commander 
  - autoreconf -if
  - ./configure
script: make && make check