#ifndef GS_CFG_KEY_H
#define GS_CFG_KEY_H

#include "gs_cfg_grp.h"

#define GS_CFG_TRUE     "1"
#define GS_CFG_FALSE    "0"

#define GS_CFG_KEY_AUTO_LOG_DETAIL_NO_GRP "autoLogDetail"
#define GS_CFG_KEY_AUTO_LOG_DETAIL GS_CFG_GRP_CHAT "/" GS_CFG_KEY_AUTO_LOG_DETAIL_NO_GRP

#define GS_CFG_KEY_LOG_NO_GRP "LOG"
#define GS_CFG_KEY_LOG GS_CFG_GRP_CONSOLE "/" GS_CFG_KEY_LOG_NO_GRP

#define GS_CFG_KEY_IP_NO_GRP "IP"
#define GS_CFG_KEY_IP GS_CFG_GRP_CONSOLE "/" GS_CFG_KEY_IP_NO_GRP

#define GS_CFG_KEY_IPS_NO_GRP "IPS"
#define GS_CFG_KEY_IPS GS_CFG_GRP_CONSOLE "/" GS_CFG_KEY_IPS_NO_GRP

#define GS_CFG_KEY_EVENTLOG_NO_GRP "eventlog"
#define GS_CFG_KEY_EVENTLOG GS_CFG_GRP_GAME "/" GS_CFG_KEY_EVENTLOG_NO_GRP

#define GS_CFG_KEY_EVENTLOG_KEEP_NO_GRP "eventlogkeep"
#define GS_CFG_KEY_EVENTLOG_KEEP GS_CFG_GRP_GAME "/" GS_CFG_KEY_EVENTLOG_KEEP_NO_GRP

#define GS_CFG_KEY_EVENTLOG_HOUSE_NO_GRP "eventlogHouse"
#define GS_CFG_KEY_EVENTLOG_HOUSE GS_CFG_GRP_GAME "/" GS_CFG_KEY_EVENTLOG_HOUSE_NO_GRP

#define GS_CFG_KEY_CHECK_RUNTIME_NO_GRP "checkRuntime"
#define GS_CFG_KEY_CHECK_RUNTIME GS_CFG_GRP_NET "/" GS_CFG_KEY_CHECK_RUNTIME_NO_GRP

#define GS_CFG_KEY_SERVER_CHANNELS_NO_GRP "serverChannels"
#define GS_CFG_KEY_SERVER_CHANNELS GS_CFG_GRP_NET "/" GS_CFG_KEY_SERVER_CHANNELS_NO_GRP

#define GS_CFG_KEY_SERVER_NAME_NO_GRP "serverName"
#define GS_CFG_KEY_SERVER_NAME GS_CFG_GRP_NET "/" GS_CFG_KEY_SERVER_NAME_NO_GRP

#define GS_CFG_KEY_SERVER_DESCR_NO_GRP "serverDescription"
#define GS_CFG_KEY_SERVER_DESCR GS_CFG_GRP_NET "/" GS_CFG_KEY_SERVER_DESCR_NO_GRP

#endif // GS_CFG_KEY_H
