#ifndef SYS_CFG_KEY_H
#define SYS_CFG_KEY_H

#include "sys_cfg_grp.h"

#define SYS_CFG_LANG_EN "en"
#define SYS_CFG_LANG_RU "ru"

#define SYS_CFG_KEY_LANG_NO_GRP "lang"
#define SYS_CFG_KEY_LANG SYS_CFG_GRP_GENERAL "/" SYS_CFG_KEY_LANG_NO_GRP

#define SYS_CFG_KEY_SERVER_NAME_NO_GRP "name"
#define SYS_CFG_KEY_SERVER_NAME SYS_CFG_GRP_GENERAL "/" SYS_CFG_KEY_SERVER_NAME_NO_GRP

#define SYS_CFG_KEY_SERVER_DESCR_NO_GRP "descr"
#define SYS_CFG_KEY_SERVER_DESCR SYS_CFG_GRP_GENERAL "/" SYS_CFG_KEY_SERVER_DESCR_NO_GRP

#endif // SYS_CFG_KEY_H
